// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOjVySYTyFIQPDEf71eXEqFb97OfhtePo',
    appId: '1:797207624780:web:52aecf92fd7b3f8d0588e9',
    messagingSenderId: '797207624780',
    projectId: 'capstoneproject-d4959',
    authDomain: 'capstoneproject-d4959.firebaseapp.com',
    storageBucket: 'capstoneproject-d4959.firebasestorage.app',
    measurementId: 'G-HQ6VRHKMST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ9vXu2DPAfZZHFmK0xghUiUbOa23MMnM',
    appId: '1:797207624780:android:a273918379e00a5f0588e9',
    messagingSenderId: '797207624780',
    projectId: 'capstoneproject-d4959',
    storageBucket: 'capstoneproject-d4959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt2s4UjnPatR73BAUckqHmXZiIuxr1zAM',
    appId: '1:797207624780:ios:c6271ac3669e9c600588e9',
    messagingSenderId: '797207624780',
    projectId: 'capstoneproject-d4959',
    storageBucket: 'capstoneproject-d4959.firebasestorage.app',
    iosBundleId: 'com.example.coecons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt2s4UjnPatR73BAUckqHmXZiIuxr1zAM',
    appId: '1:797207624780:ios:c6271ac3669e9c600588e9',
    messagingSenderId: '797207624780',
    projectId: 'capstoneproject-d4959',
    storageBucket: 'capstoneproject-d4959.firebasestorage.app',
    iosBundleId: 'com.example.coecons',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOjVySYTyFIQPDEf71eXEqFb97OfhtePo',
    appId: '1:797207624780:web:61e3f919fb38fa9e0588e9',
    messagingSenderId: '797207624780',
    projectId: 'capstoneproject-d4959',
    authDomain: 'capstoneproject-d4959.firebaseapp.com',
    storageBucket: 'capstoneproject-d4959.firebasestorage.app',
    measurementId: 'G-CRBB32R3XG',
  );
}
